version: '3.7'
services:
  server:
    image: node:23-alpine3.20
    init: true
    ports:
      - "8086:8086"
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    environment:
      HOST: 0.0.0.0
    command: /bin/sh -c "npm install && npm run dev"
    container_name: backend-server
    depends_on:
      - database
  database:
    image: mariadb:11.4
    ports:
      - "3307:3306"
    container_name: db
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}